# Generated by Django 2.2.6 on 2019-12-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_squashed_0010_image_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='video',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
