# Generated by Django 2.1.1 on 2020-01-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_auto_20200104_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
