# Generated by Django 2.1.1 on 2020-01-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_auto_20200104_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
